//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadesTaller
    {
        public int IdAct { get; set; }
        public string Actividad { get; set; }
        public string TiempoEstimado { get; set; }
        public string Formato { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FCreo { get; set; }
        public Nullable<int> IdUsCreo { get; set; }
        public Nullable<System.DateTime> FMod { get; set; }
        public Nullable<int> IdUsMod { get; set; }
        public Nullable<System.DateTime> FCan { get; set; }
        public Nullable<int> IdUsCan { get; set; }
    }
}
