//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraRol
    {
        public int IdRol { get; set; }
        public string CodBitad { get; set; }
        public string Fecha { get; set; }
        public string Turno { get; set; }
        public string Ruta { get; set; }
        public string Unidad { get; set; }
        public string Servicio { get; set; }
        public string Operador { get; set; }
    }
}
