//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.DomiciliosClientes = new HashSet<DomiciliosClientes>();
        }
    
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string FechaAlta { get; set; }
        public string Rfc { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public Nullable<int> CIDCLIENTEPROV { get; set; }
        public string CCODIGOCLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomiciliosClientes> DomiciliosClientes { get; set; }
    }
}
