//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosFlujos
    {
        public int IdConcepto { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdRubro { get; set; }
    }
}
