//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteDiarioBomba
    {
        public int IdCorte { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string HoraInicio { get; set; }
        public Nullable<double> LitrosInicio { get; set; }
        public string FotoInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string HoraFinal { get; set; }
        public Nullable<double> LitrosFinal { get; set; }
        public string FotoFinal { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelo { get; set; }
    }
}
