//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionesRequisiciones
    {
        public int IdCotizacion { get; set; }
        public Nullable<int> IdDetalleReq { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaAut { get; set; }
        public Nullable<int> IdUsAut { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<int> IdUsCreo { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> IdUsMod { get; set; }
        public Nullable<System.DateTime> FechaCan { get; set; }
        public Nullable<int> IdUsCan { get; set; }
        public Nullable<int> IdOCompra { get; set; }
    }
}
