//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosNominaEmpleados
    {
        public int IdNomina { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdBitad { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public string Tarjeta { get; set; }
        public string MetodoN1 { get; set; }
        public string MetodoN2 { get; set; }
    }
}
