//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeduccionesCheckin
    {
        public int IdDeduccion { get; set; }
        public string IdDeduccionCheckin { get; set; }
        public string Empleado { get; set; }
        public string Deduccion { get; set; }
        public Nullable<double> Total { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
