//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilioEmpleados
    {
        public int IdDomicilioEmp { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdBitad { get; set; }
        public string Calle { get; set; }
        public string NoInt { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
    }
}
