//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposComputo
    {
        public int IdEquipoComputo { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Ram { get; set; }
        public string Procesador { get; set; }
        public string Almacenamiento { get; set; }
        public string SN { get; set; }
        public string Color { get; set; }
        public string Caracteristicas { get; set; }
        public string Detalles { get; set; }
        public string Accesorios { get; set; }
        public string ValorComercial { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
