//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasOC
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdOCompra { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FolioFactura { get; set; }
        public string Ruta { get; set; }
        public string FileNFactura { get; set; }
        public string FileNXml { get; set; }
    }
}
