//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herramientas
    {
        public int IdHerramienta { get; set; }
        public string CIDPROD { get; set; }
        public string Herramienta { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<int> IdMedida { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    }
}
