//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistBajasEmp
    {
        public int IdBaja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdUsCreo { get; set; }
        public Nullable<System.DateTime> FCreo { get; set; }
        public Nullable<int> IdUsMod { get; set; }
        public Nullable<System.DateTime> FMod { get; set; }
        public Nullable<int> IdUsCan { get; set; }
        public Nullable<System.DateTime> FCan { get; set; }
    }
}
