//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SITEntities : DbContext
    {
        public SITEntities()
            : base("name=SITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<DomiciliosClientes> DomiciliosClientes { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<EstatusRutas> EstatusRutas { get; set; }
        public virtual DbSet<EstatusUsuarios> EstatusUsuarios { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<TiposRutas> TiposRutas { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<DatosNominaEmpleados> DatosNominaEmpleados { get; set; }
        public virtual DbSet<DomicilioEmpleados> DomicilioEmpleados { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<EstatusLineas> EstatusLineas { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Lineas> Lineas { get; set; }
        public virtual DbSet<EquiposComputo> EquiposComputo { get; set; }
        public virtual DbSet<EquiposMovil> EquiposMovil { get; set; }
        public virtual DbSet<Trabajadores> Trabajadores { get; set; }
        public virtual DbSet<EstatusEquipos> EstatusEquipos { get; set; }
        public virtual DbSet<UsuariosSitios> UsuariosSitios { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<ConceptosFlujos> ConceptosFlujos { get; set; }
        public virtual DbSet<Flujos> Flujos { get; set; }
        public virtual DbSet<MetodosFlujos> MetodosFlujos { get; set; }
        public virtual DbSet<RubrosFlujos> RubrosFlujos { get; set; }
        public virtual DbSet<TiposFlujos> TiposFlujos { get; set; }
        public virtual DbSet<TiposCostos> TiposCostos { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<EstatusVE> EstatusVE { get; set; }
        public virtual DbSet<ViajesEspeciales> ViajesEspeciales { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Movimientos> Movimientos { get; set; }
        public virtual DbSet<BitacoraBitad> BitacoraBitad { get; set; }
        public virtual DbSet<BitacoraRol> BitacoraRol { get; set; }
        public virtual DbSet<NotasMovimientos> NotasMovimientos { get; set; }
    }
}
