//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int IdMovimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdMetodo { get; set; }
        public string Cliente { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string Ruta { get; set; }
        public string Comprobante { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelacion { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public string NumCheque { get; set; }
    }
}
