//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomGenCheckin
    {
        public int IdNom { get; set; }
        public string IdNomCheckin { get; set; }
        public string Empleado { get; set; }
        public Nullable<System.DateTime> FInicial { get; set; }
        public Nullable<System.DateTime> FFinal { get; set; }
        public Nullable<int> TotServ { get; set; }
        public Nullable<int> TotSencillos { get; set; }
        public Nullable<int> TotRedondos { get; set; }
        public Nullable<int> TotTaxis { get; set; }
        public Nullable<int> TotEsp { get; set; }
        public Nullable<double> Salario { get; set; }
        public Nullable<double> Deducciones { get; set; }
        public Nullable<double> Bonos { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
