//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizasUnidades
    {
        public int IdPoliza { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string NumPoliza { get; set; }
        public Nullable<double> Costo { get; set; }
        public string Endoso { get; set; }
        public string Inciso { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<System.DateTime> FVencimiento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelacion { get; set; }
    }
}
