//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosSnack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosSnack()
        {
            this.Snack = new HashSet<Snack>();
        }
    
        public int IdProducto { get; set; }
        public string Producto { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<int> IdMedida { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<int> IdUsuarioCancelo { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
    
        public virtual EstatusPSnack EstatusPSnack { get; set; }
        public virtual Medidas Medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Snack> Snack { get; set; }
    }
}
