//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public Nullable<int> CIDPRODUCTO { get; set; }
        public string CodigoProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<double> Precio1 { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> Precio3 { get; set; }
        public Nullable<double> Precio4 { get; set; }
        public Nullable<double> Precio5 { get; set; }
        public Nullable<double> Precio6 { get; set; }
        public Nullable<double> Precio7 { get; set; }
        public Nullable<double> Precio8 { get; set; }
        public Nullable<double> Precio9 { get; set; }
        public Nullable<double> Precio10 { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public string RfcCliente { get; set; }
    }
}
