//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        public int IdRuta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string Unidad { get; set; }
        public string FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public string FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public string FechaCancelacion { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public string CodigoBitad { get; set; }
        public Nullable<int> PEntrada { get; set; }
        public Nullable<int> PSalida { get; set; }
    }
}
