//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosCheckin
    {
        public int IdServicio { get; set; }
        public string IdServicioCheckin { get; set; }
        public Nullable<System.DateTime> FServicio { get; set; }
        public string HServicio { get; set; }
        public string Cliente { get; set; }
        public string Ruta { get; set; }
        public string Turno { get; set; }
        public string Tipo { get; set; }
        public string Unidad { get; set; }
        public string Empleado { get; set; }
        public string ATarde { get; set; }
    }
}
