//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snack
    {
        public int IdSnack { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<double> PrecioU { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelo { get; set; }
    
        public virtual EstatusSnack EstatusSnack { get; set; }
        public virtual ProductosSnack ProductosSnack { get; set; }
        public virtual TipoPagoSnack TipoPagoSnack { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
