//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsCheckin
    {
        public int IdTicket { get; set; }
        public string IdTicketCheckin { get; set; }
        public string Unidad { get; set; }
        public string Empleado { get; set; }
        public Nullable<System.DateTime> FInicial { get; set; }
        public Nullable<System.DateTime> FFinal { get; set; }
        public Nullable<double> Litros { get; set; }
        public Nullable<double> RendReq { get; set; }
        public Nullable<double> KmGpsAnt { get; set; }
        public Nullable<double> KmGps { get; set; }
        public Nullable<double> KmGpsRec { get; set; }
        public Nullable<double> RendGps { get; set; }
    }
}
