//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int IdTicket { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<int> IdEstacion { get; set; }
        public Nullable<int> IdCombustible { get; set; }
        public Nullable<double> Litros { get; set; }
        public Nullable<double> Odometro { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelo { get; set; }
    
        public virtual Combustibles Combustibles { get; set; }
        public virtual EstacionesCombustible EstacionesCombustible { get; set; }
        public virtual Tickets Tickets1 { get; set; }
        public virtual Tickets Tickets2 { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
