//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajadores()
        {
            this.Lineas = new HashSet<Lineas>();
            this.UsuariosSitios = new HashSet<UsuariosSitios>();
        }
    
        public int IdEmpleado { get; set; }
        public Nullable<int> IdBitad { get; set; }
        public string Nombre { get; set; }
        public string Apellidop { get; set; }
        public string ApellidoM { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<int> IdDepto { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdSamsara { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lineas> Lineas { get; set; }
        public virtual Puestos Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosSitios> UsuariosSitios { get; set; }
    }
}
