//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unidades()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int IdUnidad { get; set; }
        public string Economico { get; set; }
        public string Placa { get; set; }
        public string NSerie { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdMotor { get; set; }
        public Nullable<double> RendReq { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public string Color { get; set; }
        public Nullable<int> Pasajeros { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> IdUsuarioCancelo { get; set; }
        public string Ruta { get; set; }
        public string FileFactura { get; set; }
        public string FileTCirculacion { get; set; }
        public string FilePolizaSeguro { get; set; }
        public string FileArrendamiento { get; set; }
        public string FileConstancia { get; set; }
        public string FileRefrendo { get; set; }
    
        public virtual EstatusUnidades EstatusUnidades { get; set; }
        public virtual ModelosUnidades ModelosUnidades { get; set; }
        public virtual MotoresUnidades MotoresUnidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual TipoUnidades TipoUnidades { get; set; }
    }
}
