//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosSitios
    {
        public int IdUs { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Sitio { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
