//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellidop { get; set; }
        public string Apellidom { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdDepto { get; set; }
        public string FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public string FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public string FechaCancelacion { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
