//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajesEspeciales
    {
        public int IdViaje { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Anticipo { get; set; }
        public Nullable<double> Pendiente { get; set; }
        public Nullable<int> IdMetodo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public string HoraSalida { get; set; }
        public string HoraLLegada { get; set; }
        public string Telefono { get; set; }
    }
}
